name: Python application

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry==1.0
        poetry install

    - name: Lint with isort
      run: |
        poetry run isort -rc app
    - name: Lint with black
      run: |
        poetry run black --check app
    - name: Lint with flake8
      run: |
        poetry run flake8 app
